// Generated by build.js. Edit src/ files, then run: node build.js
const __modules = {
  "src/helpers.js": function(module, exports, __require) {
const { setIcon } = require("obsidian");

const VIEW_TYPE = "sync-deck-view";
const ICON_ID = "sync-deck";
const ICON_SVG = `
  <g fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">
    <rect x="16" y="20" width="30" height="24" rx="5" />
    <rect x="54" y="20" width="30" height="24" rx="5" />
    <rect x="35" y="56" width="30" height="24" rx="5" />
    <path d="M46 32h8" />
    <path d="M50 44v12" />
  </g>
`;
const MAX_SYNC_FILE_SIZE = 10 * 1024 * 1024;
const IGNORE_PREFIXES = [".git/", ".trash/", "node_modules/", ".obsidian/cache/", ".obsidian/plugins/"];
const IGNORE_PATHS = [".obsidian/workspace.json", ".obsidian/workspace-mobile.json"];
const DEMO_MEMBER_EMAILS = new Set(["ismail@example.com", "maya@example.com", "deniz@example.com"]);

const DEFAULT_DATA = {
  signedIn: false,
  deviceId: "",
  vaultId: "",
  serverUrl: "https://api.syncdeck.cloud",
  authToken: "",
  serverStatus: "offline",
  user: {
    name: "Ismail Ivanov",
    email: "ismail@example.com",
    picture: "",
    color: "#8b5cf6",
  },
  workspace: "Aircraft Team",
  role: "Owner",
  syncEnabled: false,
  syncProgress: 0,
  lastSync: "",
  storageUsedMb: 0,
  storageLimitMb: 1024,
  vaultStats: {
    totalFiles: 0,
    syncableFiles: 0,
    syncedFiles: 0,
    markdownFiles: 0,
    binaryFiles: 0,
    taskDeckFiles: 0,
    ignoredFiles: 0,
    oversizedFiles: 0,
    totalBytes: 0,
    syncableBytes: 0,
    syncedBytes: 0,
  },
  syncQueue: [],
  recentFiles: [],
  members: [],
  activity: [],
};

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function uid(prefix) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function createElement(tag, className, text) {
  const element = document.createElement(tag);
  if (className) element.className = className;
  if (text !== undefined) element.textContent = text;
  return element;
}

function iconSlot(icon) {
  const slot = createElement("span", "sd-button-icon");
  try {
    setIcon(slot, icon);
  } catch (error) {
    slot.textContent = "";
  }
  return slot;
}

function textButton(icon, label, onClick, className = "") {
  const button = createElement("button", `sd-text-button ${className}`.trim());
  button.type = "button";
  button.append(iconSlot(icon), createElement("span", "", label));
  button.addEventListener("click", onClick);
  return button;
}

function iconBadge(icon, label) {
  const badge = createElement("span", "sd-icon-badge");
  badge.title = label;
  badge.append(iconSlot(icon));
  return badge;
}

function initials(name) {
  return String(name || "?")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0].toUpperCase())
    .join("") || "?";
}

function percent(value) {
  return `${Math.max(0, Math.min(100, Math.round(value || 0)))}%`;
}

function formatBytes(bytes) {
  const value = Number(bytes || 0);
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
  if (value < 1024 * 1024 * 1024) return `${(value / 1024 / 1024).toFixed(1)} MB`;
  return `${(value / 1024 / 1024 / 1024).toFixed(1)} GB`;
}

function isIgnoredPath(path) {
  return IGNORE_PATHS.includes(path) || IGNORE_PREFIXES.some((prefix) => path.startsWith(prefix));
}

function isMarkdownPath(path) {
  return /\.md$/i.test(path);
}

module.exports = {
  DEFAULT_DATA,
  DEMO_MEMBER_EMAILS,
  ICON_ID,
  ICON_SVG,
  IGNORE_PREFIXES,
  IGNORE_PATHS,
  MAX_SYNC_FILE_SIZE,
  VIEW_TYPE,
  clone,
  createElement,
  formatBytes,
  iconBadge,
  initials,
  isIgnoredPath,
  isMarkdownPath,
  percent,
  textButton,
  uid,
};

  },
  "src/view.js": function(module, exports, __require) {
const { ItemView } = require("obsidian");
const {
  ICON_ID,
  VIEW_TYPE,
  createElement,
  formatBytes,
  iconBadge,
  initials,
  percent,
  textButton,
} = __require("src/helpers.js");

class SyncDeckView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }

  getViewType() {
    return VIEW_TYPE;
  }

  getDisplayText() {
    return "SyncDeck";
  }

  getIcon() {
    return ICON_ID;
  }

  async onOpen() {
    this.render();
  }

  render() {
    const data = this.plugin.data;
    this.contentEl.replaceChildren();
    this.contentEl.addClass("sd-root");

    const toolbar = createElement("div", "sd-toolbar");
    const title = createElement("div", "sd-toolbar-title");
    title.append(createElement("h2", "", "SyncDeck"));
    title.append(this.statusPill(data.serverStatus === "online" ? "API online" : "API offline", data.serverStatus === "online" ? "good" : "muted"));
    if (data.signedIn) title.append(this.avatar(data.user, "sd-profile-avatar"));

    const actions = createElement("div", "sd-toolbar-actions");
    actions.append(
      textButton(data.signedIn ? "log-out" : "log-in", data.signedIn ? "Sign out" : "Continue with Google", () => {
        if (data.signedIn) this.plugin.signOut();
        else this.plugin.signIn();
      }, data.signedIn ? "" : "mod-cta"),
      textButton("refresh-cw", data.syncEnabled ? "Pause sync" : "Start sync", () => this.plugin.toggleSync())
    );
    toolbar.append(title, actions);

    const layout = createElement("div", "sd-layout");
    layout.append(this.renderSyncPanel(), this.renderActivityPanel());
    this.contentEl.append(toolbar, layout);
  }

  statusPill(text, tone) {
    return createElement("span", `sd-status-pill is-${tone}`, text);
  }

  renderSyncPanel() {
    const data = this.plugin.data;
    const stats = data.vaultStats;
    const panel = this.panel("Vault Sync", "cloud");
    const hasSyncedFiles = (stats.syncedFiles || 0) > 0;
    const progressLabel = data.syncEnabled || hasSyncedFiles ? percent(data.syncProgress) : "Ready";
    const progressWidth = data.syncEnabled || hasSyncedFiles ? percent(data.syncProgress) : "0%";
    const statusText = data.syncEnabled
      ? `${stats.syncedFiles || 0} / ${stats.syncableFiles} files synced`
      : `${stats.syncableFiles} files ready to sync`;
    const progress = createElement("div", "sd-progress");
    const fill = createElement("div", "sd-progress-fill");
    fill.style.width = progressWidth;
    progress.append(fill);

    const status = createElement("div", "sd-sync-status");
    status.append(
      createElement("strong", "", progressLabel),
      createElement("span", "", statusText)
    );

    const rules = createElement("div", "sd-rule-list");
    [
      `${stats.syncableFiles} files`,
      formatBytes(stats.syncableBytes),
      `${stats.syncedFiles || 0} synced`,
      data.lastSync ? `Last sync ${data.lastSync}` : "Not synced yet",
    ].forEach((item) => {
      rules.append(this.rule(item));
    });

    const actions = createElement("div", "sd-panel-actions");
    actions.append(
      textButton("scan-line", "Scan now", () => this.plugin.finishScan()),
      textButton("cloud-download", "Pull latest", () => this.plugin.pullLatest()),
      textButton("user-plus", "Invite", () => this.plugin.createInvite()),
      textButton("key-round", "Join", () => this.plugin.joinInvite())
    );

    panel.append(status, progress, rules, actions);
    return panel;
  }

  renderActivityPanel() {
    const panel = this.panel("Recent Activity", "radio");
    const list = createElement("div", "sd-activity-list");
    const queue = this.plugin.data.syncQueue || [];

    if (!queue.length) {
      const empty = createElement("div", "sd-empty-state");
      empty.append(createElement("strong", "", "No queued changes"), createElement("span", "", "Run a scan or edit a file while sync is active."));
      panel.append(empty);
      return panel;
    }

    queue.slice(0, 6).forEach((item) => {
      const row = createElement("div", "sd-activity-row");
      const marker = createElement("span", "sd-cursor-marker");
      marker.style.backgroundColor = item.status === "done" ? "#22c55e" : "#8b5cf6";
      const copy = createElement("div", "sd-activity-copy");
      const meta = `${item.action} - ${item.status} - ${item.time}`;
      copy.append(createElement("strong", "", item.path), createElement("span", "", meta));
      row.append(marker, copy);
      list.append(row);
    });

    panel.append(list);
    return panel;
  }

  panel(title, icon) {
    const panel = createElement("section", "sd-panel");
    const header = createElement("div", "sd-panel-header");
    header.append(createElement("h3", "", title), iconBadge(icon, title));
    panel.append(header);
    return panel;
  }

  avatar(person, className = "sd-avatar") {
    const avatar = createElement("span", className);
    avatar.style.backgroundColor = person.color || "#8b5cf6";

    if (person.picture) {
      const image = document.createElement("img");
      image.src = person.picture;
      image.alt = "";
      avatar.append(image);
    } else {
      avatar.textContent = initials(person.name || person.email);
    }

    return avatar;
  }

  rule(text) {
    const item = createElement("span", "sd-rule");
    item.append(createElement("span", "sd-rule-dot"), createElement("span", "", text));
    return item;
  }
}

module.exports = { SyncDeckView };

  },
  "src/settings-tab.js": function(module, exports, __require) {
const { PluginSettingTab, Setting } = require("obsidian");

class SyncDeckSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("sd-settings");

    containerEl.createEl("h2", { text: "SyncDeck" });
    containerEl.createEl("p", {
      text: "Realtime vault sync, team roles, and Task Deck collaboration.",
    });

    new Setting(containerEl)
      .setName("Dashboard")
      .setDesc("Open the SyncDeck control panel.")
      .addButton((button) => {
        button
          .setButtonText("Open")
          .setCta()
          .onClick(() => this.plugin.activateView());
      });

    new Setting(containerEl)
      .setName("Account")
      .setDesc(this.plugin.data.signedIn ? this.plugin.data.user.email : "Not signed in.")
      .addButton((button) => {
        button
          .setButtonText(this.plugin.data.signedIn ? "Sign out" : "Sign in")
          .onClick(() => this.plugin.data.signedIn ? this.plugin.signOut() : this.plugin.signIn());
      });

    new Setting(containerEl)
      .setName("API server")
      .setDesc("Cloud API server for auth and vault registration.")
      .addText((text) => {
        text
          .setPlaceholder("https://api.syncdeck.cloud")
          .setValue(this.plugin.data.serverUrl)
          .onChange(async (value) => {
            this.plugin.data.serverUrl = value.trim() || "https://api.syncdeck.cloud";
            await this.plugin.savePluginData();
          });
      })
      .addButton((button) => {
        button
          .setButtonText("Ping")
          .onClick(async () => {
            try {
              await this.plugin.pingServer();
            } catch (error) {
              this.plugin.data.serverStatus = "offline";
              await this.plugin.savePluginData();
            }
          });
      });

    new Setting(containerEl)
      .setName("Version")
      .setDesc(this.plugin.manifest.version || "0.1.0");
  }
}

module.exports = { SyncDeckSettingTab };

  },
  "src/plugin.js": function(module, exports, __require) {
const { Modal, Notice, Plugin, TFile, addIcon } = require("obsidian");
const {
  DEFAULT_DATA,
  DEMO_MEMBER_EMAILS,
  ICON_ID,
  ICON_SVG,
  MAX_SYNC_FILE_SIZE,
  VIEW_TYPE,
  clone,
  isIgnoredPath,
  isMarkdownPath,
  uid,
} = __require("src/helpers.js");
const { SyncDeckView } = __require("src/view.js");
const { SyncDeckSettingTab } = __require("src/settings-tab.js");

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  if (typeof Buffer !== "undefined") return Buffer.from(bytes).toString("base64");

  let binary = "";
  const chunkSize = 0x8000;
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunkSize));
  }
  return btoa(binary);
}

function base64ToArrayBuffer(value) {
  if (typeof Buffer !== "undefined") {
    const buffer = Buffer.from(value, "base64");
    return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
  }

  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes.buffer;
}

function isVaultAccessError(error) {
  return error && error.status === 403 && /vault access denied/i.test(error.message || "");
}

class InviteCodeModal extends Modal {
  constructor(app) {
    super(app);
    this.resolve = null;
  }

  openAndWait() {
    return new Promise((resolve) => {
      this.resolve = resolve;
      this.open();
    });
  }

  finish(value) {
    const resolve = this.resolve;
    this.resolve = null;
    this.close();
    if (resolve) resolve(value);
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("sd-invite-modal");
    contentEl.createEl("h2", { text: "Join vault" });
    contentEl.createEl("p", { text: "Paste the invite code from the vault owner." });

    const input = contentEl.createEl("input", {
      attr: {
        type: "text",
        placeholder: "Invite code",
        spellcheck: "false",
      },
    });
    input.addClass("sd-code-input");

    const actions = contentEl.createDiv({ cls: "sd-modal-actions" });
    const cancel = actions.createEl("button", { text: "Cancel" });
    const join = actions.createEl("button", { text: "Join" });
    join.addClass("mod-cta");

    const submit = () => {
      const code = input.value.trim().toUpperCase();
      if (!code) {
        input.focus();
        return;
      }
      this.finish(code);
    };

    cancel.addEventListener("click", () => this.finish(""));
    join.addEventListener("click", submit);
    input.addEventListener("keydown", (event) => {
      if (event.key === "Enter") submit();
      if (event.key === "Escape") this.finish("");
    });
    input.addEventListener("input", () => {
      input.value = input.value.toUpperCase();
    });

    window.setTimeout(() => input.focus(), 0);
  }

  onClose() {
    this.contentEl.empty();
    if (this.resolve) this.finish("");
  }
}

module.exports = class SyncDeckPlugin extends Plugin {
  async onload() {
    this.data = this.normalizeData(Object.assign(clone(DEFAULT_DATA), await this.loadData() || {}));

    addIcon(ICON_ID, ICON_SVG);
    this.registerView(VIEW_TYPE, (leaf) => new SyncDeckView(leaf, this));
    this.addSettingTab(new SyncDeckSettingTab(this.app, this));
    this.registerVaultEvents();

    this.addRibbonIcon(ICON_ID, "Open SyncDeck", () => this.activateView());
    this.addCommand({
      id: "open-sync-deck",
      name: "Open SyncDeck",
      callback: () => this.activateView(),
    });
  }

  onunload() {
    if (this.autoSyncTimer) window.clearTimeout(this.autoSyncTimer);
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }

  async activateView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    const leaf = leaves[0] || this.app.workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }

  async savePluginData() {
    await this.saveData(this.data);
    this.refreshViews();
  }

  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE).forEach((leaf) => leaf.view.render());
  }

  normalizeData(data) {
    data.user = Object.assign(clone(DEFAULT_DATA.user), data.user || {});
    data.serverUrl = data.serverUrl || DEFAULT_DATA.serverUrl;
    data.authToken = data.authToken || "";
    data.serverStatus = data.serverStatus || "offline";
    data.vaultStats = Object.assign(clone(DEFAULT_DATA.vaultStats), data.vaultStats || {});
    data.members = Array.isArray(data.members)
      ? data.members.filter((member) => member && !DEMO_MEMBER_EMAILS.has(member.email))
      : clone(DEFAULT_DATA.members);
    data.activity = Array.isArray(data.activity) ? data.activity : clone(DEFAULT_DATA.activity);
    data.deviceId = data.deviceId || uid("device");
    data.vaultId = data.vaultId || uid("vault");
    data.syncQueue = this.compactQueue(Array.isArray(data.syncQueue) ? data.syncQueue : []);
    data.recentFiles = Array.isArray(data.recentFiles) ? data.recentFiles.slice(0, 20) : [];
    if (data.signedIn && data.user.email && !DEMO_MEMBER_EMAILS.has(data.user.email)) {
      const current = {
        name: data.user.name || data.user.email,
        email: data.user.email,
        role: data.role || data.user.role || "User",
        color: data.user.color || "#8b5cf6",
        picture: data.user.picture || "",
        status: "online",
      };
      const index = data.members.findIndex((member) => member.email === current.email);
      if (index >= 0) data.members[index] = Object.assign({}, data.members[index], current);
      else data.members.unshift(current);
    }
    return data;
  }

  upsertCurrentUserMember() {
    if (!this.data.user.email) return;

    const current = {
      name: this.data.user.name || this.data.user.email,
      email: this.data.user.email,
      role: this.data.role || this.data.user.role || "User",
      color: this.data.user.color || "#8b5cf6",
      picture: this.data.user.picture || "",
      status: "online",
    };
    const index = this.data.members.findIndex((member) => member.email === current.email);
    if (index >= 0) this.data.members[index] = Object.assign({}, this.data.members[index], current);
    else this.data.members.unshift(current);
  }

  async api(path, options = {}) {
    const baseUrl = String(this.data.serverUrl || DEFAULT_DATA.serverUrl).replace(/\/+$/, "");
    const response = await fetch(`${baseUrl}${path}`, {
      method: options.method || "GET",
      headers: {
        "content-type": "application/json",
        ...(this.data.authToken ? { authorization: `Bearer ${this.data.authToken}` } : {}),
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
    });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) {
      const error = new Error(body.error || `HTTP ${response.status}`);
      error.status = response.status;
      throw error;
    }
    return body;
  }

  async waitForGoogleSession(state) {
    const startedAt = Date.now();
    while (Date.now() - startedAt < 120000) {
      await new Promise((resolve) => setTimeout(resolve, 1500));
      const session = await this.api(`/auth/google/session/${encodeURIComponent(state)}`);
      if (session.status === "complete") return session;
      if (session.status === "error") throw new Error(session.error || "Google sign in failed");
    }
    throw new Error("Google sign in timed out");
  }

  async pingServer() {
    await this.api("/health");
    this.data.serverStatus = "online";
    await this.savePluginData();
    return true;
  }

  async registerVault() {
    if (!this.data.authToken) return;
    await this.api("/vaults/register", {
      method: "POST",
      body: {
        vaultId: this.data.vaultId,
        deviceId: this.data.deviceId,
        workspace: this.data.workspace,
        stats: this.data.vaultStats,
      },
    });
  }

  async pushScanSummary() {
    if (!this.data.authToken) return;
    await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/scan`, {
      method: "POST",
      body: {
        stats: this.data.vaultStats,
        queueLength: this.data.syncQueue.length,
      },
    });
    this.data.serverStatus = "online";
  }

  async markVaultAccessDenied(action) {
    this.data.serverStatus = "online";
    this.data.syncEnabled = false;
    this.data.syncProgress = 0;
    this.data.vaultStats.syncedFiles = 0;
    this.pushQueueItem(action, "Vault access", 0, "failed: join or sign in again");
    await this.savePluginData();
    new Notice("This Google account cannot access this vault. Use Join with an invite code, or sign out and sign in as the owner.");
  }

  compactQueue(queue) {
    let keptScan = false;
    return queue.filter((item) => {
      if (item && item.action === "scan" && item.path === "Full vault") {
        if (keptScan) return false;
        keptScan = true;
      }
      return item && item.path;
    }).slice(0, 20);
  }

  registerVaultEvents() {
    this.registerEvent(this.app.vault.on("create", (file) => this.handleVaultEvent("create", file)));
    this.registerEvent(this.app.vault.on("modify", (file) => this.handleVaultEvent("modify", file)));
    this.registerEvent(this.app.vault.on("delete", (file) => this.handleVaultEvent("delete", file)));
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => this.handleVaultEvent("rename", file, oldPath)));
  }

  async isTaskDeckFile(file) {
    if (!(file instanceof TFile) || !isMarkdownPath(file.path)) return false;
    const text = await this.app.vault.cachedRead(file);
    return text.includes("kanban-card-id:") || text.includes("task-deck-board: true") || text.includes("kanban-board-id:");
  }

  async scanVault(options = {}) {
    const stats = clone(DEFAULT_DATA.vaultStats);
    const recentFiles = [];
    const syncableFiles = [];
    const files = this.app.vault.getFiles();

    for (const file of files) {
      const size = file.stat.size || 0;
      stats.totalFiles += 1;
      stats.totalBytes += size;

      if (isIgnoredPath(file.path)) {
        stats.ignoredFiles += 1;
        continue;
      }
      if (size > MAX_SYNC_FILE_SIZE) {
        stats.oversizedFiles += 1;
        continue;
      }

      stats.syncableFiles += 1;
      stats.syncableBytes += size;
      syncableFiles.push(file);
      if (isMarkdownPath(file.path)) stats.markdownFiles += 1;
      else stats.binaryFiles += 1;
      if (await this.isTaskDeckFile(file)) stats.taskDeckFiles += 1;

      recentFiles.push({
        path: file.path,
        size,
        mtime: file.stat.mtime || 0,
        type: isMarkdownPath(file.path) ? "markdown" : "file",
      });
    }

    recentFiles.sort((a, b) => b.mtime - a.mtime);
    this.data.vaultStats = stats;
    this.data.recentFiles = recentFiles.slice(0, 8);
    this.data.storageUsedMb = Math.round(stats.syncableBytes / 1024 / 1024);
    this.data.syncProgress = options.upload ? 0 : 100;
    this.data.lastSync = new Date().toLocaleString();
    this.pushQueueItem("scan", "Full vault", stats.syncableBytes, "done");
    try {
      await this.registerVault();
      await this.pushScanSummary();
      if (options.upload) await this.uploadVaultFiles(syncableFiles);
    } catch (error) {
      if (isVaultAccessError(error)) {
        await this.markVaultAccessDenied("sync");
        return false;
      }
      this.data.serverStatus = "offline";
      this.pushQueueItem("sync", "Server sync", 0, `failed: ${error.message}`);
      new Notice(`Server sync failed: ${error.message}`);
      await this.savePluginData();
      return false;
    }
    await this.savePluginData();
    return true;
  }

  async uploadVaultFiles(files) {
    if (!this.data.authToken) return;

    let syncedFiles = 0;
    let syncedBytes = 0;
    const paths = [];

    for (const file of files) {
      const contentBase64 = arrayBufferToBase64(await this.app.vault.readBinary(file));
      await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/files`, {
        method: "POST",
        body: {
          deviceId: this.data.deviceId,
          files: [{
            path: file.path,
            size: file.stat.size || 0,
            mtime: file.stat.mtime || 0,
            ctime: file.stat.ctime || 0,
            type: isMarkdownPath(file.path) ? "markdown" : "file",
            contentBase64,
          }],
        },
      });

      syncedFiles += 1;
      syncedBytes += file.stat.size || 0;
      paths.push(file.path);
    }

    await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/files/prune`, {
      method: "POST",
      body: { paths },
    });

    this.data.vaultStats.syncedFiles = syncedFiles;
    this.data.vaultStats.syncedBytes = syncedBytes;
    this.data.syncProgress = files.length ? Math.round((syncedFiles / files.length) * 100) : 100;
    this.data.serverStatus = "online";
    this.data.syncQueue = this.data.syncQueue.filter((item) => !(item.status === "pending" && paths.includes(item.path)));
    this.pushQueueItem("upload", "Vault files", syncedBytes, "done");
    await this.pushScanSummary();
  }

  async ensureParentFolder(filePath) {
    const parts = filePath.split("/").filter(Boolean);
    parts.pop();

    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(current)) await this.app.vault.createFolder(current);
    }
  }

  async pullLatest() {
    if (!this.data.signedIn) {
      new Notice("Sign in first.");
      return;
    }

    try {
      await this.registerVault();
      const manifest = await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/files`);
      let pulledFiles = 0;
      let pulledBytes = 0;

      for (const remoteFile of manifest.files || []) {
        if (!remoteFile.path || isIgnoredPath(remoteFile.path)) continue;

        const localFile = this.app.vault.getAbstractFileByPath(remoteFile.path);
        if (localFile instanceof TFile && (localFile.stat.mtime || 0) >= (remoteFile.mtime || 0)) continue;

        const remote = await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/files/content?path=${encodeURIComponent(remoteFile.path)}`);
        const content = base64ToArrayBuffer(remote.contentBase64);
        await this.ensureParentFolder(remoteFile.path);

        if (localFile instanceof TFile) await this.app.vault.modifyBinary(localFile, content);
        else await this.app.vault.createBinary(remoteFile.path, content);

        pulledFiles += 1;
        pulledBytes += remoteFile.size || 0;
      }

      this.data.serverStatus = "online";
      this.data.lastSync = new Date().toLocaleString();
      this.pushQueueItem("pull", "Remote vault", pulledBytes, "done");
      await this.scanVault();
      new Notice(pulledFiles ? `Pulled ${pulledFiles} files.` : "Vault already up to date.");
    } catch (error) {
      if (isVaultAccessError(error)) {
        await this.markVaultAccessDenied("pull");
        return;
      }
      this.data.serverStatus = "offline";
      this.pushQueueItem("pull", "Remote vault", 0, `failed: ${error.message}`);
      await this.savePluginData();
      new Notice(`Pull failed: ${error.message}`);
    }
  }

  pushQueueItem(action, path, size = 0, status = "pending", oldPath = "") {
    this.data.syncQueue = this.data.syncQueue.filter((item) => {
      if (action === "scan" && path === "Full vault") return !(item.action === "scan" && item.path === "Full vault");
      return !(item.action === action && item.path === path && item.status === status);
    });
    this.data.syncQueue.unshift({
      action,
      path,
      oldPath,
      size,
      status,
      time: new Date().toLocaleTimeString(),
    });
    this.data.syncQueue = this.compactQueue(this.data.syncQueue);
  }

  async handleVaultEvent(action, file, oldPath = "") {
    if (!this.data.syncEnabled) return;
    const path = file && file.path ? file.path : oldPath;
    if (!path || isIgnoredPath(path)) return;

    const size = file instanceof TFile ? file.stat.size || 0 : 0;
    if (size > MAX_SYNC_FILE_SIZE) {
      this.pushQueueItem("skip", path, size, "too large", oldPath);
    } else {
      this.pushQueueItem(action, path, size, "pending", oldPath);
    }
    await this.savePluginData();
    this.scheduleAutoSync();
  }

  scheduleAutoSync() {
    if (this.autoSyncTimer) window.clearTimeout(this.autoSyncTimer);
    this.autoSyncTimer = window.setTimeout(async () => {
      this.autoSyncTimer = null;
      if (!this.data.signedIn || !this.data.syncEnabled) return;
      if (this.autoSyncRunning) return this.scheduleAutoSync();

      this.autoSyncRunning = true;
      try {
        await this.scanVault({ upload: true });
      } finally {
        this.autoSyncRunning = false;
      }
    }, 2000);
  }

  async signIn() {
    try {
      const start = await this.api("/auth/google/start");
      if (!start.authUrl || !start.state) throw new Error("Google sign in did not start");

      window.open(start.authUrl);
      new Notice("Finish Google sign in in your browser.");

      const result = await this.waitForGoogleSession(start.state);
      const previousEmail = this.data.user.email;
      this.data.authToken = result.token;
      this.data.user = Object.assign(this.data.user, result.user || {});
      if (previousEmail && previousEmail !== this.data.user.email && !DEMO_MEMBER_EMAILS.has(previousEmail)) {
        this.data.vaultId = uid("vault");
        this.data.syncEnabled = false;
      }
      this.data.workspace = this.data.user.workspace || this.data.workspace;
      this.data.role = this.data.user.role || this.data.role;
      this.data.signedIn = true;
      this.data.serverStatus = "online";
      this.upsertCurrentUserMember();
      try {
        await this.registerVault();
      } catch (error) {
        if (error.status !== 403) throw error;
        this.data.vaultId = uid("vault");
        this.data.syncEnabled = false;
        await this.registerVault();
      }
      await this.savePluginData();
      new Notice("Signed in with Google.");
    } catch (error) {
      this.data.serverStatus = "offline";
      await this.savePluginData();
      new Notice(`Could not sign in: ${error.message}`);
    }
  }

  async signOut() {
    this.data.signedIn = false;
    this.data.syncEnabled = false;
    this.data.authToken = "";
    await this.savePluginData();
    new Notice("Signed out.");
  }

  async toggleSync() {
    if (!this.data.signedIn) {
      new Notice("Sign in first.");
      return;
    }

    this.data.syncEnabled = !this.data.syncEnabled;
    if (this.data.syncEnabled) {
      const synced = await this.scanVault({ upload: true });
      new Notice(synced ? "Vault sync started." : "Vault sync failed.");
    } else {
      await this.savePluginData();
      new Notice("Vault sync paused.");
    }
  }

  async finishScan() {
    if (!this.data.signedIn) {
      new Notice("Sign in first.");
      return;
    }

    const synced = await this.scanVault({ upload: this.data.syncEnabled });
    new Notice(synced ? (this.data.syncEnabled ? "Vault sync complete." : "Vault scan complete.") : "Vault scanned, but server sync failed.");
  }

  async createInvite() {
    if (!this.data.signedIn) {
      new Notice("Sign in first.");
      return;
    }

    try {
      await this.registerVault();
      const invite = await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/invites`, { method: "POST" });
      if (navigator.clipboard) await navigator.clipboard.writeText(invite.code).catch(() => {});
      new Notice(`Invite code copied: ${invite.code}`);
    } catch (error) {
      if (isVaultAccessError(error)) {
        await this.markVaultAccessDenied("invite");
        return;
      }
      new Notice(`Could not create invite: ${error.message}`);
    }
  }

  async joinInvite() {
    if (!this.data.signedIn) {
      new Notice("Sign in first.");
      return;
    }

    const code = await new InviteCodeModal(this.app).openAndWait();
    if (!code) return;

    try {
      const result = await this.api(`/invites/${encodeURIComponent(code.trim())}/accept`, { method: "POST" });
      this.data.vaultId = result.vaultId;
      this.data.workspace = result.workspace || this.data.workspace;
      this.data.role = result.role || "User";
      this.data.members = Array.isArray(result.members) ? result.members : this.data.members;
      await this.savePluginData();
      await this.pullLatest();
      new Notice(`Joined ${this.data.workspace}.`);
    } catch (error) {
      new Notice(`Could not join invite: ${error.message}`);
    }
  }

};

  }
};

const __cache = {};

function __require(id) {
  if (__cache[id]) return __cache[id].exports;
  const factory = __modules[id];
  if (!factory) throw new Error("Module not found: " + id);

  const module = { exports: {} };
  __cache[id] = module;
  factory(module, module.exports, __require);
  return module.exports;
}

module.exports = __require("src/plugin.js");
