// Generated by build.js. Edit src/ files, then run: node build.js
const __modules = {
  "src/helpers.js": function(module, exports, __require) {
const { setIcon } = require("obsidian");

const VIEW_TYPE = "sync-deck-view";
const ICON_ID = "sync-deck";
const ICON_SVG = `
  <g fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">
    <rect x="16" y="20" width="30" height="24" rx="5" />
    <rect x="54" y="20" width="30" height="24" rx="5" />
    <rect x="35" y="56" width="30" height="24" rx="5" />
    <path d="M46 32h8" />
    <path d="M50 44v12" />
  </g>
`;
const MAX_SYNC_FILE_SIZE = 10 * 1024 * 1024;
const IGNORE_PREFIXES = [".git/", ".trash/", "node_modules/", ".obsidian/cache/", ".obsidian/plugins/"];
const IGNORE_PATHS = [".obsidian/workspace.json", ".obsidian/workspace-mobile.json"];
const DEMO_MEMBER_EMAILS = new Set(["ismail@example.com", "maya@example.com", "deniz@example.com"]);

const DEFAULT_DATA = {
  signedIn: false,
  deviceId: "",
  vaultId: "",
  serverUrl: "https://api.syncdeck.cloud",
  authToken: "",
  serverStatus: "offline",
  user: {
    name: "Ismail Ivanov",
    email: "ismail@example.com",
    picture: "",
    color: "#8b5cf6",
  },
  workspace: "Aircraft Team",
  role: "Owner",
  syncEnabled: false,
  syncProgress: 0,
  remoteUpdatedAt: "",
  lastSync: "",
  storageUsedMb: 0,
  storageLimitMb: 1024,
  vaultStats: {
    totalFiles: 0,
    syncableFiles: 0,
    syncedFiles: 0,
    markdownFiles: 0,
    binaryFiles: 0,
    taskDeckFiles: 0,
    ignoredFiles: 0,
    oversizedFiles: 0,
    totalBytes: 0,
    syncableBytes: 0,
    syncedBytes: 0,
  },
  syncQueue: [],
  recentFiles: [],
  members: [],
  activity: [],
};

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function uid(prefix) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function createElement(tag, className, text) {
  const element = document.createElement(tag);
  if (className) element.className = className;
  if (text !== undefined) element.textContent = text;
  return element;
}

function iconSlot(icon) {
  const slot = createElement("span", "sd-button-icon");
  try {
    setIcon(slot, icon);
  } catch (error) {
    slot.textContent = "";
  }
  return slot;
}

function textButton(icon, label, onClick, className = "") {
  const button = createElement("button", `sd-text-button ${className}`.trim());
  button.type = "button";
  button.append(iconSlot(icon), createElement("span", "", label));
  button.addEventListener("click", onClick);
  return button;
}

function iconBadge(icon, label) {
  const badge = createElement("span", "sd-icon-badge");
  badge.title = label;
  badge.append(iconSlot(icon));
  return badge;
}

function initials(name) {
  return String(name || "?")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0].toUpperCase())
    .join("") || "?";
}

function percent(value) {
  return `${Math.max(0, Math.min(100, Math.round(value || 0)))}%`;
}

function formatBytes(bytes) {
  const value = Number(bytes || 0);
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
  if (value < 1024 * 1024 * 1024) return `${(value / 1024 / 1024).toFixed(1)} MB`;
  return `${(value / 1024 / 1024 / 1024).toFixed(1)} GB`;
}

function isIgnoredPath(path) {
  return IGNORE_PATHS.includes(path) || IGNORE_PREFIXES.some((prefix) => path.startsWith(prefix));
}

function isMarkdownPath(path) {
  return /\.md$/i.test(path);
}

module.exports = {
  DEFAULT_DATA,
  DEMO_MEMBER_EMAILS,
  ICON_ID,
  ICON_SVG,
  IGNORE_PREFIXES,
  IGNORE_PATHS,
  MAX_SYNC_FILE_SIZE,
  VIEW_TYPE,
  clone,
  createElement,
  formatBytes,
  iconBadge,
  initials,
  isIgnoredPath,
  isMarkdownPath,
  percent,
  textButton,
  uid,
};

  },
  "src/view.js": function(module, exports, __require) {
const { ItemView } = require("obsidian");
const {
  ICON_ID,
  VIEW_TYPE,
  createElement,
  formatBytes,
  iconBadge,
  initials,
  percent,
  textButton,
} = __require("src/helpers.js");

class SyncDeckView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }

  getViewType() {
    return VIEW_TYPE;
  }

  getDisplayText() {
    return "SyncDeck";
  }

  getIcon() {
    return ICON_ID;
  }

  async onOpen() {
    this.render();
  }

  render() {
    const data = this.plugin.data;
    this.contentEl.replaceChildren();
    this.contentEl.addClass("sd-root");

    const toolbar = createElement("div", "sd-toolbar");
    const title = createElement("div", "sd-toolbar-title");
    title.append(createElement("h2", "", "SyncDeck"));
    title.append(this.statusPill(data.serverStatus === "online" ? "API online" : "API offline", data.serverStatus === "online" ? "good" : "muted"));
    if (data.signedIn) title.append(this.avatar(data.user, "sd-profile-avatar"));

    const actions = createElement("div", "sd-toolbar-actions");
    actions.append(
      textButton(data.signedIn ? "log-out" : "log-in", data.signedIn ? "Sign out" : "Continue with Google", () => {
        if (data.signedIn) this.plugin.signOut();
        else this.plugin.signIn();
      }, data.signedIn ? "" : "mod-cta"),
      textButton("refresh-cw", data.syncEnabled ? "Pause sync" : "Start sync", () => this.plugin.toggleSync())
    );
    toolbar.append(title, actions);

    const layout = createElement("div", "sd-layout");
    layout.append(this.renderSyncPanel(), this.renderActivityPanel());
    this.contentEl.append(toolbar, layout);
  }

  statusPill(text, tone) {
    return createElement("span", `sd-status-pill is-${tone}`, text);
  }

  renderSyncPanel() {
    const data = this.plugin.data;
    const stats = data.vaultStats;
    const panel = this.panel("Vault Sync", "cloud");
    const hasSyncedFiles = (stats.syncedFiles || 0) > 0;
    const progressLabel = data.syncEnabled || hasSyncedFiles ? percent(data.syncProgress) : "Ready";
    const progressWidth = data.syncEnabled || hasSyncedFiles ? percent(data.syncProgress) : "0%";
    const statusText = data.syncEnabled
      ? `${stats.syncedFiles || 0} / ${stats.syncableFiles} files synced`
      : `${stats.syncableFiles} files ready to sync`;
    const progress = createElement("div", "sd-progress");
    const fill = createElement("div", "sd-progress-fill");
    fill.style.width = progressWidth;
    progress.append(fill);

    const status = createElement("div", "sd-sync-status");
    status.append(
      createElement("strong", "", progressLabel),
      createElement("span", "", statusText)
    );

    const rules = createElement("div", "sd-rule-list");
    [
      `${stats.syncableFiles} files`,
      formatBytes(stats.syncableBytes),
      `${stats.syncedFiles || 0} synced`,
      data.lastSync ? `Last sync ${data.lastSync}` : "Not synced yet",
    ].forEach((item) => {
      rules.append(this.rule(item));
    });

    const actions = createElement("div", "sd-panel-actions");
    actions.append(
      textButton("scan-line", "Scan now", () => this.plugin.finishScan()),
      textButton("cloud-download", "Pull latest", () => this.plugin.pullLatest()),
      textButton("user-plus", "Invite", () => this.plugin.createInvite()),
      textButton("key-round", "Join", () => this.plugin.joinInvite())
    );

    panel.append(status, progress, rules, actions);
    return panel;
  }

  renderActivityPanel() {
    const panel = this.panel("Recent Activity", "radio");
    const list = createElement("div", "sd-activity-list");
    const queue = this.plugin.data.syncQueue || [];

    if (!queue.length) {
      const empty = createElement("div", "sd-empty-state");
      empty.append(createElement("strong", "", "No queued changes"), createElement("span", "", "Run a scan or edit a file while sync is active."));
      panel.append(empty);
      return panel;
    }

    queue.slice(0, 6).forEach((item) => {
      const row = createElement("div", "sd-activity-row");
      const marker = createElement("span", "sd-cursor-marker");
      marker.style.backgroundColor = item.status === "done" ? "#22c55e" : "#8b5cf6";
      const copy = createElement("div", "sd-activity-copy");
      const meta = `${item.action} - ${item.status} - ${item.time}`;
      copy.append(createElement("strong", "", item.path), createElement("span", "", meta));
      row.append(marker, copy);
      list.append(row);
    });

    panel.append(list);
    return panel;
  }

  panel(title, icon) {
    const panel = createElement("section", "sd-panel");
    const header = createElement("div", "sd-panel-header");
    header.append(createElement("h3", "", title), iconBadge(icon, title));
    panel.append(header);
    return panel;
  }

  avatar(person, className = "sd-avatar") {
    const avatar = createElement("span", className);
    avatar.style.backgroundColor = person.color || "#8b5cf6";

    if (person.picture) {
      const image = document.createElement("img");
      image.src = person.picture;
      image.alt = "";
      avatar.append(image);
    } else {
      avatar.textContent = initials(person.name || person.email);
    }

    return avatar;
  }

  rule(text) {
    const item = createElement("span", "sd-rule");
    item.append(createElement("span", "sd-rule-dot"), createElement("span", "", text));
    return item;
  }
}

module.exports = { SyncDeckView };

  },
  "src/settings-tab.js": function(module, exports, __require) {
const { PluginSettingTab, Setting } = require("obsidian");

class SyncDeckSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("sd-settings");

    containerEl.createEl("h2", { text: "SyncDeck" });
    containerEl.createEl("p", {
      text: "Realtime vault sync, team roles, and Task Deck collaboration.",
    });

    new Setting(containerEl)
      .setName("Dashboard")
      .setDesc("Open the SyncDeck control panel.")
      .addButton((button) => {
        button
          .setButtonText("Open")
          .setCta()
          .onClick(() => this.plugin.activateView());
      });

    new Setting(containerEl)
      .setName("Account")
      .setDesc(this.plugin.data.signedIn ? this.plugin.data.user.email : "Not signed in.")
      .addButton((button) => {
        button
          .setButtonText(this.plugin.data.signedIn ? "Sign out" : "Sign in")
          .onClick(() => this.plugin.data.signedIn ? this.plugin.signOut() : this.plugin.signIn());
      });

    new Setting(containerEl)
      .setName("API server")
      .setDesc("Cloud API server for auth and vault registration.")
      .addText((text) => {
        text
          .setPlaceholder("https://api.syncdeck.cloud")
          .setValue(this.plugin.data.serverUrl)
          .onChange(async (value) => {
            this.plugin.data.serverUrl = value.trim() || "https://api.syncdeck.cloud";
            await this.plugin.savePluginData();
          });
      })
      .addButton((button) => {
        button
          .setButtonText("Ping")
          .onClick(async () => {
            try {
              await this.plugin.pingServer();
            } catch (error) {
              this.plugin.data.serverStatus = "offline";
              await this.plugin.savePluginData();
            }
          });
      });

    new Setting(containerEl)
      .setName("Version")
      .setDesc(this.plugin.manifest.version || "0.1.0");
  }
}

module.exports = { SyncDeckSettingTab };

  },
  "src/editor-presence.js": function(module, exports, __require) {
const { MarkdownView } = require("obsidian");
const { isMarkdownPath, isIgnoredPath } = __require("src/helpers.js");

// Live editor presence: shows other members' cursors in the file you both have
// open, and a status-bar note that they are there. It is deliberately built as
// an absolutely-positioned overlay driven by the editor's read-only coordsAtPos
// API — it never mutates the editor, so a bug here cannot break typing.
const SEND_ACTIVE_MS = 180; // presence post interval while others are present
const SEND_IDLE_MS = 1500; // interval while alone (still refresh + detect peers)

class EditorPresence {
  constructor(plugin) {
    this.plugin = plugin;
    this.currentPath = null;
    this.currentView = null;
    this.editor = null;
    this.peers = new Map();
    this.layer = null;
    this.statusEl = null;
    this.timer = null;
    this.renderRaf = null;
    this.scrollEl = null;
    this.onMoveBound = null;
    this.scrollSettle = null;
    this.inFlight = false;
    this.disposed = false;
    this.tickBound = () => this.tick();
  }

  start() {
    try {
      this.statusEl = this.plugin.addStatusBarItem();
      this.statusEl.addClass("sd-presence-status");
      this.renderStatus();
      this.plugin.registerEvent(this.plugin.app.workspace.on("active-leaf-change", () => this.onActiveChange()));
      this.plugin.registerEvent(this.plugin.app.workspace.on("layout-change", () => this.onActiveChange()));
      this.onActiveChange();
    } catch (error) {
      // presence is best-effort; never let it break plugin load
    }
  }

  stop() {
    this.disposed = true;
    if (this.currentPath && this.isEnabled()) this.sendLeave(this.currentPath);
    this.teardown();
    if (this.statusEl && this.statusEl.parentElement) this.statusEl.remove();
    this.statusEl = null;
    this.currentPath = null;
    this.currentView = null;
    this.peers = new Map();
  }

  isEnabled() {
    const d = this.plugin.data;
    return !!(d && d.signedIn && d.authToken && d.vaultId && typeof this.plugin.api === "function");
  }

  getActive() {
    const view = this.plugin.app.workspace.getActiveViewOfType(MarkdownView);
    if (!view || !view.file) return null;
    const path = view.file.path;
    if (isIgnoredPath(path) || !isMarkdownPath(path)) return null;
    return { view, path, editor: view.editor };
  }

  onActiveChange() {
    const active = this.getActive();
    const path = active ? active.path : null;
    if (path === this.currentPath) {
      if (active) { this.currentView = active.view; this.editor = active.editor; }
      return;
    }
    if (this.currentPath && this.isEnabled()) this.sendLeave(this.currentPath);
    this.teardown();
    this.currentPath = path;
    this.currentView = active ? active.view : null;
    this.editor = active ? active.editor : null;
    this.peers = new Map();
    if (path && this.isEnabled()) {
      this.setupLayer();
      this.scheduleTick(0);
    }
    this.renderStatus();
  }

  setupLayer() {
    try {
      this.layer = document.createElement("div");
      this.layer.className = "sd-editor-cursors";
      document.body.appendChild(this.layer);
      // Re-place carets only when the view actually moves (scroll/resize), never
      // on a per-frame loop — the old per-frame coordsAtPos was what made the
      // editor jank. On scroll we drop the CSS transition so carets track exactly.
      const cm = this.editor && this.editor.cm;
      this.scrollEl = cm && cm.scrollDOM ? cm.scrollDOM : null;
      this.onMoveBound = () => {
        if (this.layer) {
          this.layer.classList.add("is-scrolling");
          if (this.scrollSettle) window.clearTimeout(this.scrollSettle);
          this.scrollSettle = window.setTimeout(() => {
            if (this.layer) this.layer.classList.remove("is-scrolling");
          }, 150);
        }
        this.scheduleRender();
      };
      if (this.scrollEl) this.scrollEl.addEventListener("scroll", this.onMoveBound, { passive: true });
      window.addEventListener("resize", this.onMoveBound, { passive: true });
    } catch (error) {
      this.layer = null;
    }
  }

  teardown() {
    if (this.timer) { window.clearTimeout(this.timer); this.timer = null; }
    if (this.renderRaf != null) { cancelAnimationFrame(this.renderRaf); this.renderRaf = null; }
    if (this.scrollSettle) { window.clearTimeout(this.scrollSettle); this.scrollSettle = null; }
    if (this.onMoveBound) {
      if (this.scrollEl) this.scrollEl.removeEventListener("scroll", this.onMoveBound);
      window.removeEventListener("resize", this.onMoveBound);
    }
    this.scrollEl = null;
    this.onMoveBound = null;
    if (this.layer && this.layer.parentElement) this.layer.remove();
    this.layer = null;
    this.editor = null;
    this.inFlight = false;
  }

  scheduleTick(delay) {
    if (this.disposed) return;
    if (this.timer) window.clearTimeout(this.timer);
    const d = typeof delay === "number" ? delay : (this.peers.size ? SEND_ACTIVE_MS : SEND_IDLE_MS);
    this.timer = window.setTimeout(this.tickBound, d);
  }

  readCursor() {
    try {
      const c = this.editor && this.editor.getCursor ? this.editor.getCursor() : null;
      const editing = this.currentView && this.currentView.getMode ? this.currentView.getMode() === "source" : true;
      return { line: (c && c.line) || 0, ch: (c && c.ch) || 0, editing };
    } catch (error) {
      return { line: 0, ch: 0, editing: false };
    }
  }

  async tick() {
    this.timer = null;
    // No file / torn down: stop the chain (do NOT self-reschedule, or a settled
    // in-flight request could keep this timer alive forever after teardown).
    if (this.disposed || !this.currentPath) return;
    if (!this.isEnabled()) { this.scheduleTick(SEND_IDLE_MS); return; }
    if (this.inFlight) { this.scheduleTick(); return; }

    const path = this.currentPath;
    const cur = this.readCursor();
    const color = (this.plugin.data.user && this.plugin.data.user.color) || "#8b5cf6";
    this.inFlight = true;
    try {
      const result = await this.plugin.api(`/vaults/${encodeURIComponent(this.plugin.data.vaultId)}/files/presence`, {
        method: "POST",
        body: { path, line: cur.line, ch: cur.ch, editing: cur.editing, color },
      });
      if (!this.disposed && this.currentPath === path) this.applyPeers(result && result.peers);
    } catch (error) {
      // offline / server hiccup: keep the last known peers rather than clearing
    } finally {
      this.inFlight = false;
      if (!this.disposed && this.currentPath) this.scheduleTick();
    }
  }

  async sendLeave(path) {
    try {
      await this.plugin.api(`/vaults/${encodeURIComponent(this.plugin.data.vaultId)}/files/presence`, {
        method: "POST",
        body: { path, leave: true },
      });
    } catch (error) {
      // best-effort; the server TTL expires us anyway
    }
  }

  applyPeers(peers) {
    if (!Array.isArray(peers)) return;
    const seen = new Set();
    peers.forEach((p) => {
      if (!p || !p.email || !Number.isFinite(p.line) || !Number.isFinite(p.ch)) return;
      seen.add(p.email);
      let entry = this.peers.get(p.email);
      if (!entry) { entry = {}; this.peers.set(p.email, entry); }
      entry.name = p.name || p.email;
      entry.color = p.color || "#8b5cf6";
      entry.editing = !!p.editing;
      entry.line = p.line;
      entry.ch = p.ch;
    });
    // The server returns all active peers, so anyone absent has left -> remove.
    this.peers.forEach((entry, email) => {
      if (seen.has(email)) return;
      if (entry.el && entry.el.parentElement) entry.el.remove();
      this.peers.delete(email);
    });
    this.renderStatus();
    this.scheduleRender();
  }

  // Coalesce redraws into a single rAF. Called only on real changes (a presence
  // update, scroll, or resize) — NOT every frame — so there is no idle CPU cost.
  scheduleRender() {
    if (this.disposed || this.renderRaf != null || !this.layer) return;
    this.renderRaf = requestAnimationFrame(() => {
      this.renderRaf = null;
      this.renderCursors();
    });
  }

  renderCursors() {
    if (!this.layer || !this.editor || this.peers.size === 0) return;
    const cm = this.editor.cm;
    const scrollRect = cm && cm.scrollDOM ? cm.scrollDOM.getBoundingClientRect() : null;
    this.peers.forEach((entry) => {
      const px = this.coordsFor(entry);
      const visible = !!(px && scrollRect
        && px.top >= scrollRect.top - 2 && px.top + px.h <= scrollRect.bottom + 2
        && px.left >= scrollRect.left - 2 && px.left <= scrollRect.right + 2);
      this.drawCaret(entry, px, visible);
    });
  }

  coordsFor(entry) {
    try {
      const cm = this.editor.cm;
      if (!cm || typeof cm.coordsAtPos !== "function" || !this.editor.posToOffset) return null;
      const offset = this.editor.posToOffset({ line: entry.line, ch: entry.ch });
      if (offset == null) return null;
      const c = cm.coordsAtPos(offset);
      if (!c) return null;
      return { left: c.left, top: c.top, h: Math.max(12, c.bottom - c.top) };
    } catch (error) {
      return null;
    }
  }

  drawCaret(entry, px, visible) {
    if (!visible) {
      if (entry.el) entry.el.style.display = "none";
      return;
    }
    if (!entry.el) {
      entry.el = document.createElement("div");
      entry.el.className = "sd-editor-cursor";
      entry.caret = document.createElement("span");
      entry.caret.className = "sd-editor-caret";
      entry.label = document.createElement("span");
      entry.label.className = "sd-editor-name";
      entry.el.append(entry.caret, entry.label);
      this.layer.append(entry.el);
    }
    if (entry.label.textContent !== entry.name) entry.label.textContent = entry.name;
    entry.el.style.setProperty("--sd-cursor-color", entry.color || "#8b5cf6");
    entry.el.style.height = `${px.h.toFixed(0)}px`;
    entry.el.style.display = "";
    entry.el.style.transform = `translate(${px.left.toFixed(1)}px, ${px.top.toFixed(1)}px)`;
  }

  renderStatus() {
    if (!this.statusEl) return;
    const count = this.peers.size;
    if (!this.currentPath || count === 0) {
      this.statusEl.setText("");
      this.statusEl.style.display = "none";
      return;
    }
    const editing = Array.from(this.peers.values()).filter((p) => p.editing).map((p) => p.name);
    this.statusEl.style.display = "";
    this.statusEl.setText(editing.length ? `✍ ${editing.join(", ")} editing` : `\u{1F441} ${count} here`);
  }
}

module.exports = { EditorPresence };

  },
  "src/plugin.js": function(module, exports, __require) {
const { Modal, Notice, Plugin, TFile, addIcon } = require("obsidian");
const {
  DEFAULT_DATA,
  DEMO_MEMBER_EMAILS,
  ICON_ID,
  ICON_SVG,
  MAX_SYNC_FILE_SIZE,
  VIEW_TYPE,
  clone,
  isIgnoredPath,
  isMarkdownPath,
  uid,
} = __require("src/helpers.js");
const { SyncDeckView } = __require("src/view.js");
const { SyncDeckSettingTab } = __require("src/settings-tab.js");
const { EditorPresence } = __require("src/editor-presence.js");

const REMOTE_POLL_INTERVAL_MS = 1200; // idle poll (nobody else on the open file)
const REMOTE_POLL_ACTIVE_MS = 400; // fast poll while collaborating on the open file

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  if (typeof Buffer !== "undefined") return Buffer.from(bytes).toString("base64");

  let binary = "";
  const chunkSize = 0x8000;
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunkSize));
  }
  return btoa(binary);
}

function base64ToArrayBuffer(value) {
  if (typeof Buffer !== "undefined") {
    const buffer = Buffer.from(value, "base64");
    return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
  }

  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes.buffer;
}

function isVaultAccessError(error) {
  return error && error.status === 403 && /vault access denied/i.test(error.message || "");
}

class InviteCodeModal extends Modal {
  constructor(app) {
    super(app);
    this.resolve = null;
  }

  openAndWait() {
    return new Promise((resolve) => {
      this.resolve = resolve;
      this.open();
    });
  }

  finish(value) {
    const resolve = this.resolve;
    this.resolve = null;
    this.close();
    if (resolve) resolve(value);
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("sd-invite-modal");
    contentEl.createEl("h2", { text: "Join vault" });
    contentEl.createEl("p", { text: "Paste the invite code from the vault owner." });

    const input = contentEl.createEl("input", {
      attr: {
        type: "text",
        placeholder: "Invite code",
        spellcheck: "false",
      },
    });
    input.addClass("sd-code-input");

    const actions = contentEl.createDiv({ cls: "sd-modal-actions" });
    const cancel = actions.createEl("button", { text: "Cancel" });
    const join = actions.createEl("button", { text: "Join" });
    join.addClass("mod-cta");

    const submit = () => {
      const code = input.value.trim().toUpperCase();
      if (!code) {
        input.focus();
        return;
      }
      this.finish(code);
    };

    cancel.addEventListener("click", () => this.finish(""));
    join.addEventListener("click", submit);
    input.addEventListener("keydown", (event) => {
      if (event.key === "Enter") submit();
      if (event.key === "Escape") this.finish("");
    });
    input.addEventListener("input", () => {
      input.value = input.value.toUpperCase();
    });

    window.setTimeout(() => input.focus(), 0);
  }

  onClose() {
    this.contentEl.empty();
    if (this.resolve) this.finish("");
  }
}

module.exports = class SyncDeckPlugin extends Plugin {
  async onload() {
    this.data = this.normalizeData(Object.assign(clone(DEFAULT_DATA), await this.loadData() || {}));

    addIcon(ICON_ID, ICON_SVG);
    this.registerView(VIEW_TYPE, (leaf) => new SyncDeckView(leaf, this));
    this.addSettingTab(new SyncDeckSettingTab(this.app, this));
    this.registerVaultEvents();

    this.addRibbonIcon(ICON_ID, "Open SyncDeck", () => this.activateView());
    this.addCommand({
      id: "open-sync-deck",
      name: "Open SyncDeck",
      callback: () => this.activateView(),
    });
    this.startRemotePolling();
    this.editorPresence = new EditorPresence(this);
    this.editorPresence.start();
  }

  onunload() {
    this.unloaded = true;
    if (this.autoSyncTimer) window.clearTimeout(this.autoSyncTimer);
    if (this.remotePollTimer) window.clearTimeout(this.remotePollTimer);
    if (this.editorPresence) this.editorPresence.stop();
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }

  async activateView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    const leaf = leaves[0] || this.app.workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }

  async savePluginData() {
    await this.saveData(this.data);
    this.refreshViews();
  }

  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE).forEach((leaf) => leaf.view.render());
  }

  normalizeData(data) {
    data.user = Object.assign(clone(DEFAULT_DATA.user), data.user || {});
    data.serverUrl = data.serverUrl || DEFAULT_DATA.serverUrl;
    data.authToken = data.authToken || "";
    data.serverStatus = data.serverStatus || "offline";
    data.remoteUpdatedAt = data.remoteUpdatedAt || "";
    data.vaultStats = Object.assign(clone(DEFAULT_DATA.vaultStats), data.vaultStats || {});
    data.members = Array.isArray(data.members)
      ? data.members.filter((member) => member && !DEMO_MEMBER_EMAILS.has(member.email))
      : clone(DEFAULT_DATA.members);
    data.activity = Array.isArray(data.activity) ? data.activity : clone(DEFAULT_DATA.activity);
    data.deviceId = data.deviceId || uid("device");
    data.vaultId = data.vaultId || uid("vault");
    data.syncQueue = this.compactQueue(Array.isArray(data.syncQueue) ? data.syncQueue : []);
    data.recentFiles = Array.isArray(data.recentFiles) ? data.recentFiles.slice(0, 20) : [];
    data.remoteKnownPaths = Array.isArray(data.remoteKnownPaths) ? data.remoteKnownPaths : [];
    data.remoteKnownVaultId = typeof data.remoteKnownVaultId === "string" ? data.remoteKnownVaultId : "";
    data.pendingDeletes = Array.isArray(data.pendingDeletes) ? data.pendingDeletes : [];
    data.deferredDeletePath = typeof data.deferredDeletePath === "string" ? data.deferredDeletePath : null;
    if (data.signedIn && data.user.email && !DEMO_MEMBER_EMAILS.has(data.user.email)) {
      const current = {
        name: data.user.name || data.user.email,
        email: data.user.email,
        role: data.role || data.user.role || "User",
        color: data.user.color || "#8b5cf6",
        picture: data.user.picture || "",
        status: "online",
      };
      const index = data.members.findIndex((member) => member.email === current.email);
      if (index >= 0) data.members[index] = Object.assign({}, data.members[index], current);
      else data.members.unshift(current);
    }
    return data;
  }

  upsertCurrentUserMember() {
    if (!this.data.user.email) return;

    const current = {
      name: this.data.user.name || this.data.user.email,
      email: this.data.user.email,
      role: this.data.role || this.data.user.role || "User",
      color: this.data.user.color || "#8b5cf6",
      picture: this.data.user.picture || "",
      status: "online",
    };
    const index = this.data.members.findIndex((member) => member.email === current.email);
    if (index >= 0) this.data.members[index] = Object.assign({}, this.data.members[index], current);
    else this.data.members.unshift(current);
  }

  async api(path, options = {}) {
    const baseUrl = String(this.data.serverUrl || DEFAULT_DATA.serverUrl).replace(/\/+$/, "");
    const response = await fetch(`${baseUrl}${path}`, {
      method: options.method || "GET",
      headers: {
        "content-type": "application/json",
        ...(this.data.authToken ? { authorization: `Bearer ${this.data.authToken}` } : {}),
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
    });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) {
      const error = new Error(body.error || `HTTP ${response.status}`);
      error.status = response.status;
      throw error;
    }
    return body;
  }

  async waitForGoogleSession(state) {
    const startedAt = Date.now();
    while (Date.now() - startedAt < 120000) {
      await new Promise((resolve) => setTimeout(resolve, 1500));
      const session = await this.api(`/auth/google/session/${encodeURIComponent(state)}`);
      if (session.status === "complete") return session;
      if (session.status === "error") throw new Error(session.error || "Google sign in failed");
    }
    throw new Error("Google sign in timed out");
  }

  async pingServer() {
    await this.api("/health");
    this.data.serverStatus = "online";
    await this.savePluginData();
    return true;
  }

  async registerVault() {
    if (!this.data.authToken) return;
    await this.api("/vaults/register", {
      method: "POST",
      body: {
        vaultId: this.data.vaultId,
        deviceId: this.data.deviceId,
        workspace: this.data.workspace,
        stats: this.data.vaultStats,
      },
    });
  }

  async pushScanSummary() {
    if (!this.data.authToken) return;
    await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/scan`, {
      method: "POST",
      body: {
        stats: this.data.vaultStats,
        queueLength: this.data.syncQueue.length,
      },
    });
    this.data.serverStatus = "online";
  }

  async markVaultAccessDenied(action) {
    this.data.serverStatus = "online";
    this.data.syncEnabled = false;
    this.data.syncProgress = 0;
    this.data.vaultStats.syncedFiles = 0;
    this.pushQueueItem(action, "Vault access", 0, "failed: join or sign in again");
    await this.savePluginData();
    new Notice("This Google account cannot access this vault. Use Join with an invite code, or sign out and sign in as the owner.");
  }

  compactQueue(queue) {
    let keptScan = false;
    return queue.filter((item) => {
      if (item && item.action === "scan" && item.path === "Full vault") {
        if (keptScan) return false;
        keptScan = true;
      }
      return item && item.path;
    }).slice(0, 20);
  }

  registerVaultEvents() {
    this.registerEvent(this.app.vault.on("create", (file) => this.handleVaultEvent("create", file)));
    this.registerEvent(this.app.vault.on("modify", (file) => this.handleVaultEvent("modify", file)));
    this.registerEvent(this.app.vault.on("delete", (file) => this.handleVaultEvent("delete", file)));
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => this.handleVaultEvent("rename", file, oldPath)));
  }

  async isTaskDeckFile(file) {
    if (!(file instanceof TFile) || !isMarkdownPath(file.path)) return false;
    const text = await this.app.vault.cachedRead(file);
    return text.includes("kanban-card-id:") || text.includes("task-deck-board: true") || text.includes("kanban-board-id:");
  }

  async scanVault(options = {}) {
    const stats = clone(DEFAULT_DATA.vaultStats);
    const recentFiles = [];
    const syncableFiles = [];
    const files = this.app.vault.getFiles();

    for (const file of files) {
      const size = file.stat.size || 0;
      stats.totalFiles += 1;
      stats.totalBytes += size;

      if (isIgnoredPath(file.path)) {
        stats.ignoredFiles += 1;
        continue;
      }
      if (size > MAX_SYNC_FILE_SIZE) {
        stats.oversizedFiles += 1;
        continue;
      }

      stats.syncableFiles += 1;
      stats.syncableBytes += size;
      syncableFiles.push(file);
      if (isMarkdownPath(file.path)) stats.markdownFiles += 1;
      else stats.binaryFiles += 1;
      if (await this.isTaskDeckFile(file)) stats.taskDeckFiles += 1;

      recentFiles.push({
        path: file.path,
        size,
        mtime: file.stat.mtime || 0,
        type: isMarkdownPath(file.path) ? "markdown" : "file",
      });
    }

    recentFiles.sort((a, b) => b.mtime - a.mtime);
    this.data.vaultStats = stats;
    this.data.recentFiles = recentFiles.slice(0, 8);
    this.data.storageUsedMb = Math.round(stats.syncableBytes / 1024 / 1024);
    this.data.syncProgress = options.upload ? 0 : 100;
    this.data.lastSync = new Date().toLocaleString();
    this.pushQueueItem("scan", "Full vault", stats.syncableBytes, "done");
    try {
      await this.registerVault();
      await this.pushScanSummary();
      if (options.upload) await this.uploadVaultFiles(syncableFiles, { incremental: options.incremental });
    } catch (error) {
      if (isVaultAccessError(error)) {
        await this.markVaultAccessDenied("sync");
        return false;
      }
      this.data.serverStatus = "offline";
      this.pushQueueItem("sync", "Server sync", 0, `failed: ${error.message}`);
      new Notice(`Server sync failed: ${error.message}`);
      await this.savePluginData();
      return false;
    }
    await this.savePluginData();
    return true;
  }

  // The set of paths this device believes exist on the server. It is tagged with
  // the vaultId it was recorded for; if the active vault differs (e.g. after
  // joining another vault or switching accounts) it is treated as empty, so a
  // stale baseline can never drive a deletion against the new vault's files.
  getRemoteKnownPaths() {
    if (this.data.remoteKnownVaultId !== this.data.vaultId) return new Set();
    return new Set(this.data.remoteKnownPaths || []);
  }

  setRemoteKnownPaths(paths) {
    this.data.remoteKnownPaths = Array.isArray(paths) ? paths : Array.from(paths);
    this.data.remoteKnownVaultId = this.data.vaultId;
  }

  async uploadVaultFiles(files, options = {}) {
    if (!this.data.authToken) return;

    // Incremental uploads skip files whose content is unchanged since the last
    // sync, so a single card edit uploads one file instead of the whole vault.
    // A full (non-incremental) upload rebuilds the signature cache from scratch,
    // which is what manual / toggle / first-time sync uses as a safety net.
    const incremental = !!options.incremental;
    const previous = this.uploadedSignatures || {};
    const nextSignatures = {};
    // Paths that fired a local vault event since the last sync must upload even
    // if their signature looks unchanged. Snapshot so events during this run are
    // kept for the next sync rather than dropped.
    const dirty = new Set(this.dirtyUploadPaths || []);

    let syncedFiles = 0;
    let syncedBytes = 0;
    const paths = [];
    const failed = new Set();

    for (const file of files) {
      const signature = `${file.stat.mtime || 0}:${file.stat.size || 0}`;
      if (incremental && previous[file.path] === signature && !dirty.has(file.path)) {
        paths.push(file.path); // unchanged -> already on the server
        nextSignatures[file.path] = signature;
        continue;
      }

      try {
        const contentBase64 = arrayBufferToBase64(await this.app.vault.readBinary(file));
        await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/files`, {
          method: "POST",
          body: {
            deviceId: this.data.deviceId,
            files: [{
              path: file.path,
              size: file.stat.size || 0,
              mtime: file.stat.mtime || 0,
              ctime: file.stat.ctime || 0,
              type: isMarkdownPath(file.path) ? "markdown" : "file",
              contentBase64,
            }],
          },
        });
        paths.push(file.path);
        nextSignatures[file.path] = signature;
        syncedFiles += 1;
        syncedBytes += file.stat.size || 0;
      } catch (error) {
        // One file failing must not abort the whole sync. Leave it un-synced: not
        // in `paths` (so it is never recorded as on-server, which would let the
        // pull trash it), no signature (retries next sync), and left dirty.
        failed.add(file.path);
      }
    }
    this.uploadedSignatures = nextSignatures;
    if (this.dirtyUploadPaths) dirty.forEach((path) => { if (!failed.has(path)) this.dirtyUploadPaths.delete(path); });
    if (failed.size) this.pushQueueItem("upload", `${failed.size} file(s) will retry`, 0, "retry");

    // Explicitly delete only the files THIS device intentionally removed: paths
    // we knew were on the server, that fired a local delete/rename event, and that
    // are still gone now. This never touches another device's not-yet-synced files
    // (unlike a full prune), leaves oversized files (still present) alone, and
    // ignores an atomic-save remove/rewrite blip (no delete event for the path).
    const known = this.getRemoteKnownPaths();
    const sameVault = this.data.remoteKnownVaultId === this.data.vaultId;
    const pending = new Set(sameVault && Array.isArray(this.data.pendingDeletes) ? this.data.pendingDeletes : []);
    const toDelete = Array.from(known).filter(
      (path) => pending.has(path) && !this.app.vault.getAbstractFileByPath(path)
    );
    if (toDelete.length) {
      await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/files/delete`, {
        method: "POST",
        body: { paths: toDelete },
      });
    }
    const deletedSet = new Set(toDelete);
    const nextKnown = new Set(known);
    paths.forEach((path) => nextKnown.add(path));
    deletedSet.forEach((path) => nextKnown.delete(path));
    this.setRemoteKnownPaths(Array.from(nextKnown));
    // Keep only intents that are still unresolved: path still gone locally and
    // still believed present on the server. Deleted, reappeared, or never-remote
    // paths drop out, so the set cannot grow without bound.
    if (sameVault) {
      this.data.pendingDeletes = Array.from(pending).filter(
        (path) => nextKnown.has(path) && !this.app.vault.getAbstractFileByPath(path)
      );
    }

    this.data.vaultStats.syncedFiles = syncedFiles;
    this.data.vaultStats.syncedBytes = syncedBytes;
    this.data.syncProgress = files.length ? Math.round((syncedFiles / files.length) * 100) : 100;
    this.data.serverStatus = "online";
    this.data.syncQueue = this.data.syncQueue.filter((item) => !(item.status === "pending" && paths.includes(item.path)));
    this.pushQueueItem("upload", "Vault files", syncedBytes, "done");
    await this.pushScanSummary();
  }

  async ensureParentFolder(filePath) {
    const parts = filePath.split("/").filter(Boolean);
    parts.pop();

    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(current)) await this.app.vault.createFolder(current);
    }
  }

  startRemotePolling() {
    if (this.remotePollTimer) window.clearTimeout(this.remotePollTimer);
    const loop = async () => {
      try {
        await this.pollRemoteChanges();
      } catch (error) {
        // pollRemoteChanges handles its own errors; never let the loop die
      }
      if (this.unloaded) return; // do not re-arm after the plugin was unloaded
      // Poll fast while someone else is on the same file (active collaboration),
      // relaxed otherwise, so changes feel near-instant without constant load.
      const collaborating = this.editorPresence && this.editorPresence.peers && this.editorPresence.peers.size > 0;
      this.remotePollTimer = window.setTimeout(loop, collaborating ? REMOTE_POLL_ACTIVE_MS : REMOTE_POLL_INTERVAL_MS);
    };
    this.remotePollTimer = window.setTimeout(loop, REMOTE_POLL_ACTIVE_MS);
  }

  async pollRemoteChanges() {
    if (!this.data.signedIn || !this.data.syncEnabled) return;
    if (this.autoSyncRunning || this.remotePullRunning) return;

    try {
      await this.registerVault();
      const manifest = await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/files`);
      if (!manifest.updatedAt || manifest.updatedAt === this.data.remoteUpdatedAt) return;
      await this.pullLatest({ manifest, silent: true });
    } catch (error) {
      if (isVaultAccessError(error)) {
        await this.markVaultAccessDenied("poll");
        return;
      }
      this.data.serverStatus = "offline";
      this.pushQueueItem("pull", "Remote vault", 0, `failed: ${error.message}`);
      await this.savePluginData();
    }
  }

  async pullLatest(options = {}) {
    if (!this.data.signedIn) {
      if (!options.silent) new Notice("Sign in first.");
      return;
    }
    if (this.remotePullRunning) return;

    this.remotePullRunning = true;
    try {
      await this.registerVault();
      const manifest = options.manifest || await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/files`);
      let pulledFiles = 0;
      let pulledBytes = 0;
      let trashedFiles = 0;
      // Skip pulling/trashing a file that has un-uploaded LOCAL edits (dirty), so
      // we never clobber the user's own unsaved work — but DO sync a file the user
      // is only viewing, so others' edits and deletions show up live.
      const dirty = this.dirtyUploadPaths || new Set();
      // Snapshot the known-set at entry so a concurrent upload cannot make a
      // just-added path look like a remote deletion mid-pull.
      const known = this.getRemoteKnownPaths();

      // Paths this pull writes/trashes. Used to tell our own vault events apart
      // from a genuine user delete that races the pull (see handleVaultEvent).
      this.pullTouchedPaths = new Set();

      this.applyingRemoteChanges = true;
      try {
        for (const remoteFile of manifest.files || []) {
          if (!remoteFile.path || isIgnoredPath(remoteFile.path)) continue;
          if (dirty.has(remoteFile.path)) continue;

          const localFile = this.app.vault.getAbstractFileByPath(remoteFile.path);
          if (localFile instanceof TFile && (localFile.stat.mtime || 0) >= (remoteFile.mtime || 0)) continue;

          this.pullTouchedPaths.add(remoteFile.path);
          const remote = await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/files/content?path=${encodeURIComponent(remoteFile.path)}`);
          const content = base64ToArrayBuffer(remote.contentBase64);
          await this.ensureParentFolder(remoteFile.path);

          if (localFile instanceof TFile) await this.app.vault.modifyBinary(localFile, content);
          else await this.app.vault.createBinary(remoteFile.path, content);

          // Record the pulled file's post-write signature so the next incremental
          // upload treats it as already-synced instead of echoing it back to the
          // server with a bumped local mtime (which would ping-pong between devices).
          const writtenFile = this.app.vault.getAbstractFileByPath(remoteFile.path);
          if (writtenFile instanceof TFile) {
            this.uploadedSignatures = this.uploadedSignatures || {};
            this.uploadedSignatures[remoteFile.path] = `${writtenFile.stat.mtime || 0}:${writtenFile.stat.size || 0}`;
          }

          pulledFiles += 1;
          pulledBytes += remoteFile.size || 0;
        }

        // Propagate remote deletions: a file we previously knew on the server but
        // that is gone from the manifest was deleted elsewhere -> trash ours too.
        // remoteKnownPaths distinguishes "deleted remotely" from "new locally".
        const remotePaths = new Set(
          (manifest.files || [])
            .filter((file) => file.path && !isIgnoredPath(file.path))
            .map((file) => file.path)
        );
        // Conservative trash: only remove a local file that is genuinely gone
        // from the server. Skip anything that (a) still exists on the server under
        // a different case (case-only rename on a case-insensitive filesystem) or
        // (b) the user has locally re-created/edited and not yet uploaded — either
        // would destroy content the user did not delete.
        const remotePathsLower = new Set(Array.from(remotePaths, (p) => p.toLowerCase()));
        for (const file of this.app.vault.getFiles()) {
          if (isIgnoredPath(file.path)) continue;
          if (remotePaths.has(file.path) || !known.has(file.path)) continue;
          if (remotePathsLower.has(file.path.toLowerCase())) continue;
          if (dirty.has(file.path)) continue;
          try {
            this.pullTouchedPaths.add(file.path);
            await this.app.vault.trash(file, false);
            if (this.uploadedSignatures) delete this.uploadedSignatures[file.path];
            trashedFiles += 1;
          } catch (error) {
            // ignore individual delete failures; a later pull retries
          }
        }
        // New baseline is the server truth (the manifest).
        this.setRemoteKnownPaths(Array.from(remotePaths));
      } finally {
        this.pullTouchedPaths = null;
        this.applyingRemoteChanges = false;
      }

      this.data.serverStatus = "online";
      this.data.remoteUpdatedAt = manifest.updatedAt || this.data.remoteUpdatedAt;
      this.data.lastSync = new Date().toLocaleString();
      this.pushQueueItem("pull", "Remote vault", pulledBytes, "done");
      await this.scanVault();
      if (!options.silent) {
        const summary = [
          pulledFiles ? `Pulled ${pulledFiles} files` : "",
          trashedFiles ? `removed ${trashedFiles}` : "",
        ].filter(Boolean).join(", ");
        new Notice(summary ? `${summary}.` : "Vault already up to date.");
      }
    } catch (error) {
      if (isVaultAccessError(error)) {
        await this.markVaultAccessDenied("pull");
        return;
      }
      this.data.serverStatus = "offline";
      this.pushQueueItem("pull", "Remote vault", 0, `failed: ${error.message}`);
      await this.savePluginData();
      if (!options.silent) new Notice(`Pull failed: ${error.message}`);
    } finally {
      this.remotePullRunning = false;
    }
  }

  pushQueueItem(action, path, size = 0, status = "pending", oldPath = "") {
    this.data.syncQueue = this.data.syncQueue.filter((item) => {
      if (action === "scan" && path === "Full vault") return !(item.action === "scan" && item.path === "Full vault");
      return !(item.action === action && item.path === path && item.status === status);
    });
    this.data.syncQueue.unshift({
      action,
      path,
      oldPath,
      size,
      status,
      time: new Date().toLocaleTimeString(),
    });
    this.data.syncQueue = this.compactQueue(this.data.syncQueue);
  }

  async handleVaultEvent(action, file, oldPath = "") {
    const path = file && file.path ? file.path : oldPath;
    if (this.applyingRemoteChanges) {
      // Our own pull fires create/modify/delete events. Ignore those (they are in
      // pullTouchedPaths), but still handle genuine USER changes racing the pull:
      const survivor = action !== "delete" && file && file.path ? file.path : null;
      // Protect a path the user created/renamed-INTO during the pull from the
      // trash loop, which would otherwise destroy that fresh content.
      if (survivor && !isIgnoredPath(survivor) && !(this.pullTouchedPaths && this.pullTouchedPaths.has(survivor))) {
        this.dirtyUploadPaths = this.dirtyUploadPaths || new Set();
        this.dirtyUploadPaths.add(survivor);
      }
      // Capture a user delete/rename so the removal is not silently swallowed.
      if (action === "delete" || action === "rename") {
        const gone = action === "rename" ? oldPath : path;
        if (gone && !isIgnoredPath(gone) && !(this.pullTouchedPaths && this.pullTouchedPaths.has(gone))) {
          this.data.pendingDeletes = Array.isArray(this.data.pendingDeletes) ? this.data.pendingDeletes : [];
          if (!this.data.pendingDeletes.includes(gone)) this.data.pendingDeletes.push(gone);
        }
      }
      return;
    }
    if (!this.data.syncEnabled) return;
    if (!path || isIgnoredPath(path)) return;

    // A locally-originated change is always uploaded on the next sync, even if
    // its mtime/size signature happens to match the cache (incremental guard).
    this.dirtyUploadPaths = this.dirtyUploadPaths || new Set();
    this.dirtyUploadPaths.add(path);

    // Record intentional local removals durably in this.data (survives reload)
    // so a genuine deletion still propagates after a restart, while a create/modify
    // for the same path cancels the intent — so an atomic-save remove/rewrite blip
    // never becomes a deletion.
    this.data.pendingDeletes = Array.isArray(this.data.pendingDeletes) ? this.data.pendingDeletes : [];
    const addPendingDelete = (p) => { if (p && !this.data.pendingDeletes.includes(p)) this.data.pendingDeletes.push(p); };
    const dropPendingDelete = (p) => { this.data.pendingDeletes = this.data.pendingDeletes.filter((x) => x !== p); };
    if (action === "delete") addPendingDelete(path);
    else if (action === "rename") { if (oldPath && !isIgnoredPath(oldPath)) addPendingDelete(oldPath); dropPendingDelete(path); }
    else dropPendingDelete(path); // create/modify => the file exists; cancel any stale delete intent

    const size = file instanceof TFile ? file.stat.size || 0 : 0;
    if (size > MAX_SYNC_FILE_SIZE) {
      this.pushQueueItem("skip", path, size, "too large", oldPath);
    } else {
      this.pushQueueItem(action, path, size, "pending", oldPath);
    }
    await this.savePluginData();
    this.scheduleAutoSync();
  }

  scheduleAutoSync() {
    if (this.autoSyncTimer) window.clearTimeout(this.autoSyncTimer);
    this.autoSyncTimer = window.setTimeout(async () => {
      this.autoSyncTimer = null;
      if (this.unloaded) return;
      if (!this.data.signedIn || !this.data.syncEnabled) return;
      // Never run an upload while a pull is in flight: both mutate remoteKnownPaths
      // and an interleave can misread a just-uploaded file as a remote deletion.
      if (this.autoSyncRunning || this.remotePullRunning) return this.scheduleAutoSync();

      this.autoSyncRunning = true;
      try {
        await this.scanVault({ upload: true, incremental: true });
      } finally {
        this.autoSyncRunning = false;
      }
    }, 250);
  }

  async signIn() {
    try {
      const start = await this.api("/auth/google/start");
      if (!start.authUrl || !start.state) throw new Error("Google sign in did not start");

      window.open(start.authUrl);
      new Notice("Finish Google sign in in your browser.");

      const result = await this.waitForGoogleSession(start.state);
      const previousEmail = this.data.user.email;
      this.data.authToken = result.token;
      this.data.user = Object.assign(this.data.user, result.user || {});
      if (previousEmail && previousEmail !== this.data.user.email && !DEMO_MEMBER_EMAILS.has(previousEmail)) {
        this.data.vaultId = uid("vault");
        this.data.syncEnabled = false;
      }
      this.data.workspace = this.data.user.workspace || this.data.workspace;
      this.data.role = this.data.user.role || this.data.role;
      this.data.signedIn = true;
      this.data.serverStatus = "online";
      this.upsertCurrentUserMember();
      try {
        await this.registerVault();
      } catch (error) {
        if (error.status !== 403) throw error;
        this.data.vaultId = uid("vault");
        this.data.syncEnabled = false;
        await this.registerVault();
      }
      await this.savePluginData();
      new Notice("Signed in with Google.");
    } catch (error) {
      this.data.serverStatus = "offline";
      await this.savePluginData();
      new Notice(`Could not sign in: ${error.message}`);
    }
  }

  async signOut() {
    this.data.signedIn = false;
    this.data.syncEnabled = false;
    this.data.authToken = "";
    await this.savePluginData();
    new Notice("Signed out.");
  }

  async toggleSync() {
    if (!this.data.signedIn) {
      new Notice("Sign in first.");
      return;
    }

    this.data.syncEnabled = !this.data.syncEnabled;
    if (this.data.syncEnabled) {
      const synced = await this.scanVault({ upload: true });
      new Notice(synced ? "Vault sync started." : "Vault sync failed.");
    } else {
      await this.savePluginData();
      new Notice("Vault sync paused.");
    }
  }

  async finishScan() {
    if (!this.data.signedIn) {
      new Notice("Sign in first.");
      return;
    }

    const synced = await this.scanVault({ upload: this.data.syncEnabled });
    new Notice(synced ? (this.data.syncEnabled ? "Vault sync complete." : "Vault scan complete.") : "Vault scanned, but server sync failed.");
  }

  async createInvite() {
    if (!this.data.signedIn) {
      new Notice("Sign in first.");
      return;
    }

    try {
      await this.registerVault();
      const invite = await this.api(`/vaults/${encodeURIComponent(this.data.vaultId)}/invites`, { method: "POST" });
      if (navigator.clipboard) await navigator.clipboard.writeText(invite.code).catch(() => {});
      new Notice(`Invite code copied: ${invite.code}`);
    } catch (error) {
      if (isVaultAccessError(error)) {
        await this.markVaultAccessDenied("invite");
        return;
      }
      new Notice(`Could not create invite: ${error.message}`);
    }
  }

  async joinInvite() {
    if (!this.data.signedIn) {
      new Notice("Sign in first.");
      return;
    }

    const code = await new InviteCodeModal(this.app).openAndWait();
    if (!code) return;

    try {
      const result = await this.api(`/invites/${encodeURIComponent(code.trim())}/accept`, { method: "POST" });
      this.data.vaultId = result.vaultId;
      this.data.workspace = result.workspace || this.data.workspace;
      this.data.role = result.role || "User";
      this.data.members = Array.isArray(result.members) ? result.members : this.data.members;
      await this.savePluginData();
      await this.pullLatest();
      new Notice(`Joined ${this.data.workspace}.`);
    } catch (error) {
      new Notice(`Could not join invite: ${error.message}`);
    }
  }

};

  }
};

const __cache = {};

function __require(id) {
  if (__cache[id]) return __cache[id].exports;
  const factory = __modules[id];
  if (!factory) throw new Error("Module not found: " + id);

  const module = { exports: {} };
  __cache[id] = module;
  factory(module, module.exports, __require);
  return module.exports;
}

module.exports = __require("src/plugin.js");
